apiVersion: skaffold/v2alpha3
kind: Config
metadata:
  name: skaffold-github-actions-demo
build:
  tagPolicy:
    sha256: {}
  artifacts:
    - image: pyjokes

profiles:
  - name: local
    deploy:
      kubeContext: k3d-skaffold-demo

deploy:
  kubectl:
    manifests:
      - ./k8s-manifests/**.yaml
