apiVersion: skaffold/v2alpha3
kind: Config
metadata:
  name: skaffold-github-actions-demo
build:
  local:
    push: false
  artifacts:
    - image: pyjokes
      sync:
        infer:
          - '**/*.py'
deploy:
  kubectl:
    manifests:
      - ./k8s-manifests/**.yaml
