apiVersion: apps/v1
kind: Deployment
metadata:
  name: pyjokes-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pyjokes-app
  template:
    metadata:
      labels:
        app: pyjokes-app
    spec:
      containers:
        - name: pyjokes-app
          image: pyjokes
          imagePullPolicy: IfNotPresent
