name: CI

on: [push]

jobs:
  ci:
    runs-on: ubuntu-latest

  setup:
    steps:
      - uses: actions/checkout@v2
      - run: ./scripts/setup.sh
  build:
    needs: setup
    steps:
      - uses: actions/checkout@v2
      - run: |
          pwd
          ./scripts/build.sh
          ./scripts/test.sh
  shutdown:
    needs: build
    steps:
      - uses: actions/checkout@v2
      - run: ./scripts/clean.sh
